#!/bin/bash
echo "=== HotSpot Manager - Build APK ==="
echo ""
echo "روش ۱: EAS Build (توصیه می‌شود)"
echo "-----------------------------------"
echo "1. npm install -g eas-cli"
echo "2. eas login   (نیاز به اکانت Expo دارد - رایگان)"
echo "3. eas build -p android --profile preview"
echo "   APK لینک دانلود می‌دهد"
echo ""
echo "روش ۲: Build محلی"
echo "------------------"
echo "نیاز به: Java 17، Android SDK"
echo "1. npx expo prebuild --platform android"
echo "2. cd android && ./gradlew assembleDebug"
echo "   APK در: android/app/build/outputs/apk/debug/"
